### ISSUE TITLE
Little bug in Unproject

### ISSUE THREAD

**Issue by rfilkov** [jmarcincin/MultiK2#3]
I found a little bug in the CameraIntrinsics.UnprojectFromFrame()-method. The last line should be: 'return new Vector3(x, y, depth);', because x & y are already multiplied to 'depth' one line above.

In this regard, one question bugs me for days: Do you know how to unproject a point from the color camera frame to the color space, given that the depth values are related to the depth camera frame? Maybe I'm missing something..

**Comment by jmarcincin** [comment]
thank you for identification of the "I will refactor this line right before commit" bug. 
It might be useful to add integration tests (req. Kinect) to compare CoordinationMapper of Kinect SDK or Windows Runtime CameraIntrinsics with mapping methods in the MultiK2 library - currently I am doing it by using MultiK2 in the SDK samples and comparing the output of mapping.

If your intention is to create a color point cloud or simply to color space points, you need to start from the depth frame to obtain the depth of color points because you have no idea how far is the point represented by color frame pixel.

DepthCameraIntrinsics->UnprojectFromFrame([DepthFramePosition], depth)) = [DepthSpacePoint]
CoordinateMapper->MapDepthSpacePointToColor([DepthSpacePoint]) = [ColorSpacePoint]
ColorCameraIntrinsics->ProjectOntoFrame([CameraSpacePoint]) = [ColorFramePosition] 

Considering the difference in the FoV and physical positions of cameras. You won't be able to find out depth of every color point.

Kinect SDK has methods to output a list of ColorSpacePoints/DepthSpacePoints for entire frames. I intend to add similar methods to MultiK2 in the near future.

**Comment by rfilkov** [comment]
You are welcome ;)

Yes, I know how to map the depth point to color coordinates. But what I wanted to do is the opposite: to map the entire color frame to depth coordinates, as in the K2 SDK. Just cannot figure out how to find out the depths for each color frame point. Maybe first map the depth frame to color camera space, and then interpolate between the known depths?!

**Comment by jmarcincin** [comment]
Yes that's what I was trying to convey. You have to start from the "non flat" representation of the scene (depth frame). Interpolating between color camera depth points is a bit tricky because you have less color camera space points (based on depth frame) than color camera frame points (pixels). Interpolation without color frame analysis (e.g. edge detection) would lead to bizarre interpolated pixel depths.

camera space:
S1(1000) -------- S2(2000)
color frame:
P1(1000) P2(???) P3(2000)

There is only a very low chance that P2 is 1500. This is the reason why you often see mapping of color to depth space and not the other way.

**Comment by jmarcincin** [comment]
Fixed in https://github.com/jmarcincin/MultiK2/commit/708230ee9ed68a54c9b6b229641b6c480448252a
